name: Build Windows Flutter App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.1"
          channel: stable

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Copy DLLs to build directory
        run: |
          copy C:\hostedtoolcache\windows\flutter\stable-3.29.1-x64\bin\cache\artifacts\engine\windows-x64\flutter_windows.dll build\windows\x64\runner\Release\
          copy C:\hostedtoolcache\windows\flutter\stable-3.29.1-x64\bin\cache\artifacts\engine\windows-x64\flutter_embedder.dll build\windows\x64\runner\Release\

      - name: List files in build directory
        run: dir build\windows\x64\runner\Release\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/my_desktop_app.exe
